#!/usr/bin/env bash
# Script to automate installation of nginx on a server
# Write a specific string at the root
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School ooh ool" | sudo tee /usr/share/nginx/html/index.html
