#!/usr/bin/env bash
# sets up a new nginx and redirects to nyan cat
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "36i\      rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart

