#!/usr/bin/env bash
# Install and configure HAProxy on our lb-01 server
# HAProxy uses a roundrobin algorithm by default

sudo apt-get update
sudo apt-get install haproxy
sudo sed -i 's/*ENABLED=0*/ENABLED=1/' /etc/default/haproxy

file=/etc/haproxy/haproxy.cfg

sudo cp $file $file.copy

sudo sed -i -e "$ a\listen appname 0.0.0.0:80\n\tmode http\n\tstats enable" $file
sudo sed -i -e "$ a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor" $file
sudo sed -i -e "$ a\\tserver 92-web-01 52.90.159.84:80 check\n\tserver 92-web-02 54.242.30.104:80 check" $file

sudo service haproxy start
