#!/usr/bin/env bash
#infinite loop that ignores sigterm, for learning purposes
i=0
while [ $i -lt 1 ]; do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I am invincible!!!" SIGTERM
done
