#!/usr/bin/env bash
#more sophisticated loop with case
i=0
while [ $i -lt 20 ]; do
    let i=i+1
    echo $i
    case $i in
	"4")
	echo "bad luck from China"
	;;
	"9")
	echo "bad luck from Japan"
	;;
	"17")
	echo "bad luck from Italy"
	;;
    esac
done
