#!/usr/bin/env bash
sudo cp /etc/hosts /etc/hosts.bkup
echo "127.0.0.2 localhost
127.0.0.1 92-web-01
8.8.8.8	  facebook.com
# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts" | sudo tee /etc/hosts
