#!/usr/bin/env bash
i=0
while [ $i -lt 20 ]; do
    let i=i+1
    echo $i
    if [ $i == "4" ]
	then echo "bad luck from China"
    elif [ $i == "9" ]
	then echo "bad luck from Japan"
    elif [ $i == "17" ]
	then echo "bad luck from Italy"
    fi
done
