#!/usr/bin/env bash
#prints a whole lotta time
hours=0
while [ $hours -lt 12 ]; do
    echo Hour: $hours
    let hours=hours+1
    minutes=0
    while [ $minutes -lt 59 ]; do
	let minutes=minutes+1
	echo $minutes
	done
done
